apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: python-quiz-app 
    tier: backend 
spec: 
  containers:
  - name: backend-container 
    image: nzoam93/python-app-backend
    ports:
    - containerPort: 8080 #because backend is listening on port 8080
