apiVersion: v1 
kind: Pod
metadata:
  name: db-pod
  labels:
    app: python-quiz-app 
    tier: db 
spec: 
  containers:
  - name: db-container 
    image: nzoam93/python-app-db
    env: 
    - name: POSTGRES_USER
      value: "myuser"
    - name: POSTGRES_PASSWORD
      value: "mypassword"
    - name: POSTGRES_DB
      value: "mydb"
    ports: 
    - containerPort: 5432 #because PG is listening on port 5432

      #note: these match the environment variables set in the postgres container in docker 
      #ENV POSTGRES_USER=myuser
      #ENV POSTGRES_PASSWORD=mypassword
      #ENV POSTGRES_DB=mydb