apiVersion: v1 
kind: Secret
metadata: 
  name: db-secret
data: 
  POSTGRES_USER: bXl1c2Vy 
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== 
  POSTGRES_DB: bXlkYg== 
  
#the values in secrets need to be encoded. To get the encoded values, do 
#"echo -n '<value>' | base64'