apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: python-quiz-app 
    tier: frontend 
spec: 
  containers:
  - name: frontend-container 
    image: nzoam93/python-app-frontend
    ports:
    - containerPort: 8081 #because nginx frontend listening on port 8081
